/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Grafica;

import Conectividad.FachadaCon;
import Logica.Cuenta2;
import Logica.Fachada;
import Logica.Usuario2;
import java.awt.Desktop;
import java.io.IOException;
import java.net.URL;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alejandro
 */
public class Mail extends javax.swing.JFrame {

    private String email_para = "";
    private String asunto = "";
    private String fecha = "";

    /**
     * Creates new form Mail
     */
    public Mail() {
        initComponents();
        setLocationRelativeTo(null);
        setExtendedState(MAXIMIZED_BOTH);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaMail = new javax.swing.JTable();
        labelLogo = new javax.swing.JLabel();
        btnAyuda = new javax.swing.JToggleButton();
        btnBandejaEntrada = new javax.swing.JButton();
        btnBandejaSalida = new javax.swing.JButton();
        btnElementosEnviados = new javax.swing.JButton();
        btnElementosEliminados = new javax.swing.JButton();
        btnCrearCarpetas = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnRedactar = new javax.swing.JButton();
        btnReenviar = new javax.swing.JButton();
        btnResponder1 = new javax.swing.JButton();
        btnResponderTodos = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnContactos = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tablaMail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Asunto", "De", "Fecha"
            }
        ));
        tablaMail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMailMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaMail);

        labelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/isoLaCalera.png"))); // NOI18N

        btnAyuda.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnAyuda.setText("Ayuda");
        btnAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAyudaActionPerformed(evt);
            }
        });

        btnBandejaEntrada.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnBandejaEntrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnBandejaEntrada.png"))); // NOI18N
        btnBandejaEntrada.setText("Entrada");
        btnBandejaEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBandejaEntradaActionPerformed(evt);
            }
        });

        btnBandejaSalida.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnBandejaSalida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnBandejaSalida.png"))); // NOI18N
        btnBandejaSalida.setText("Salida");

        btnElementosEnviados.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnElementosEnviados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnEnviados.jpg"))); // NOI18N
        btnElementosEnviados.setText("Enviados");

        btnElementosEliminados.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnElementosEliminados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnPapelera.png"))); // NOI18N
        btnElementosEliminados.setText("Eliminados");

        btnCrearCarpetas.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnCrearCarpetas.setText("Crear Carpeta");
        btnCrearCarpetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearCarpetasActionPerformed(evt);
            }
        });

        btnActualizar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnActualizar.setText("Actualizar");

        btnRedactar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnRedactar.setText("Redactar");
        btnRedactar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRedactarActionPerformed(evt);
            }
        });

        btnReenviar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnReenviar.setText("Reenviar");
        btnReenviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReenviarActionPerformed(evt);
            }
        });

        btnResponder1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnResponder1.setText("Responder");
        btnResponder1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResponder1ActionPerformed(evt);
            }
        });

        btnResponderTodos.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnResponderTodos.setText("Responder a todos");
        btnResponderTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResponderTodosActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnContactos.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnContactos.setText("Contactos");
        btnContactos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContactosActionPerformed(evt);
            }
        });

        jPanel2.setLayout(new java.awt.GridLayout(20, 1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 149, Short.MAX_VALUE)
                        .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRedactar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnReenviar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnResponder1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnResponderTodos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnContactos))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAyuda, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCrearCarpetas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBandejaEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBandejaSalida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnElementosEnviados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnElementosEliminados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAyuda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRedactar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnReenviar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnResponder1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnResponderTodos, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnContactos, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnBandejaEntrada)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBandejaSalida)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnElementosEnviados)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnElementosEliminados)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCrearCarpetas, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnContactosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContactosActionPerformed
        new Contactos().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnContactosActionPerformed

    private void btnReenviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReenviarActionPerformed
        new Reenviar().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnReenviarActionPerformed

    private void btnRedactarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRedactarActionPerformed
        new Redactar().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnRedactarActionPerformed

    private void btnResponder1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResponder1ActionPerformed
        if (!email_para.isEmpty()) {
            Responder r = new Responder();

//            r.setEmail_para(email_para);
//            r.setAsunto(asunto);
            r.setCorreo(Fachada.getInstancia().obtener_email_fecha(fecha));

            r.setVisible(true);
            //new Responder().setVisible(true);
            dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Primero debe seleccionar un email.");
        }
    }//GEN-LAST:event_btnResponder1ActionPerformed

    private void btnResponderTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResponderTodosActionPerformed
        new ResponderTodos().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnResponderTodosActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnBandejaEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBandejaEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBandejaEntradaActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        Fachada.getInstancia().getUsuario().getCuenta().refrescar_correos();
        FachadaCon.getInstancia().RecibeCorreo(Usuario2.getInstancia().getCuenta().getNom_cuenta(),
                Usuario2.getInstancia().getCuenta().getDominio(),
                Usuario2.getInstancia().getPassword()
        );
        tablaMail.setModel(Fachada.getInstancia().cargar_mails());
    }//GEN-LAST:event_formWindowOpened

    private void tablaMailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMailMouseClicked
        JTable src = (JTable) evt.getSource();
        int row = src.rowAtPoint(evt.getPoint());

        email_para = String.valueOf(tablaMail.getValueAt(row, 0));
        System.out.println("email_para " + email_para + "|");
        asunto = String.valueOf(tablaMail.getValueAt(row, 1));

        fecha = String.valueOf(tablaMail.getValueAt(row, 2));
    }//GEN-LAST:event_tablaMailMouseClicked

    private void btnAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAyudaActionPerformed
        try {
            Desktop.getDesktop().browse(new URL("https://lacalera.netlify.app/beepManualC.html").toURI());
        } catch (Exception e) {
            System.err.println("Error " + e);
        }
    }//GEN-LAST:event_btnAyudaActionPerformed

    private void btnCrearCarpetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearCarpetasActionPerformed

        String nombreCarpeta = JOptionPane.showInputDialog(this, "Ingrese nombre la carpeta");
        JButton boton = new JButton(nombreCarpeta);
        //Fachada.getInstancia().getUsuario().getCuenta().carpetaBD(Cuenta2.getInstancia().getNom_cuenta(), Cuenta2.getInstancia().getDominio(), Usuario2.getInstancia().getCedula(), nombreCarpeta);
        jPanel2.add(boton);
        jPanel2.updateUI();

    }//GEN-LAST:event_btnCrearCarpetasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mail().setVisible(true);
            }
        });
    }

    /*private DefaultTableModel limpiar_tabla(){
        String col[] = new 
        DefaultTableModel modelo = new DefaultTableModel();
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JToggleButton btnAyuda;
    private javax.swing.JButton btnBandejaEntrada;
    private javax.swing.JButton btnBandejaSalida;
    private javax.swing.JButton btnContactos;
    private javax.swing.JButton btnCrearCarpetas;
    private javax.swing.JButton btnElementosEliminados;
    private javax.swing.JButton btnElementosEnviados;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnRedactar;
    private javax.swing.JButton btnReenviar;
    private javax.swing.JButton btnResponder1;
    private javax.swing.JButton btnResponderTodos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelLogo;
    private javax.swing.JTable tablaMail;
    // End of variables declaration//GEN-END:variables
}
